# Generated by Django 6.0.7 on 2026-07-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='ชื่อร้านของคุณ', max_length=100, verbose_name='ชื่อร้าน')),
                ('address', models.TextField(verbose_name='ที่อยู่ร้าน')),
                ('phone', models.CharField(max_length=50, verbose_name='เบอร์โทรศัพท์')),
                ('line_id', models.CharField(blank=True, help_text='ใส่แค่ไอดี เช่น @mystore', max_length=50, null=True, verbose_name='LINE ID')),
                ('facebook_url', models.URLField(blank=True, help_text='ใส่ลิงก์ Facebook Page', max_length=255, null=True, verbose_name='Facebook URL')),
                ('google_map_embed', models.TextField(blank=True, help_text='นำโค้ดฝังแผนที่ (iframe) จาก Google Maps มาวางที่นี่', null=True, verbose_name='Google Map (Embed Code)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='อัปเดตล่าสุดเมื่อ')),
            ],
            options={
                'verbose_name': 'ตั้งค่าข้อมูลติดต่อ',
                'verbose_name_plural': 'ติดต่อเรา (ตั้งค่าร้าน)',
            },
        ),
    ]
