# Generated by Django 6.0.7 on 2026-07-24 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_name_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ชื่อ-นามสกุล')),
                ('phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.TextField(verbose_name='ที่อยู่จัดส่งวัตถุมงคล')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคารวม')),
                ('slip_image', models.ImageField(blank=True, null=True, upload_to='slips/', verbose_name='สลิปโอนเงิน')),
                ('status', models.CharField(choices=[('pending', 'รอชำระเงิน / รอตรวจสอบสลิป'), ('paid', 'ชำระเงินแล้ว / จัดเตรียมวัตถุมงคล'), ('shipped', 'จัดส่งวัตถุมงคลเรียบร้อย'), ('cancelled', 'ยกเลิกคำสั่งซื้อ')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่งซื้อ')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
