# Generated by Django 6.0.7 on 2026-07-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
            ],
            options={
                'verbose_name': 'ประวัติการขาย',
                'verbose_name_plural': 'ประวัติการขาย',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='order',
            name='line_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LINE ID (สำหรับรับแจ้งเลขพัสดุ)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขพัสดุ (Tracking No.)'),
        ),
    ]
