# Generated by Django 6.0.7 on 2026-07-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_saleshistory_order_line_id_order_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อ-นามสกุล')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('message', models.TextField(verbose_name='ข้อความ/ข้อสงสัย')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว/จัดการแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ติดต่อ')),
            ],
            options={
                'verbose_name': 'ติดต่อเรา',
                'verbose_name_plural': 'ข้อความติดต่อเรา',
                'ordering': ['-created_at'],
            },
        ),
    ]
