# Generated by Django 6.0.7 on 2026-07-23 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug (URL)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='รูปหมวดหมู่')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'ข้อมูลหมวดหมู่สินค้า',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสินค้า')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาปกติ')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ราคาลดพิเศษ')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='จำนวนในสต็อก')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดขายสินค้า')),
                ('is_featured', models.BooleanField(default=False, verbose_name='สินค้าแนะนำ')),
                ('main_image', models.ImageField(upload_to='products/mains/', verbose_name='รูปภาพหลัก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='สร้างเมื่อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='แก้ไขล่าสุด')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'ข้อมูลสินค้า',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='รูปภาพประกอบ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='products.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รูปภาพสินค้าเพิ่มเติม',
                'verbose_name_plural': 'แกลเลอรีรูปภาพสินค้า',
            },
        ),
    ]
